### PR TITLE
Fixes for running with https frontend

### PR DESCRIPTION
**Pull request by campbel**

### CODE REVIEW

**Comment by campbel** [comment]
Complete fix for https://github.com/criticalstack/quake-kube/issues/17

**Comment by alexellis** [comment]
Have you tested this?

**Comment by campbel** [comment]
Yep, I've got my patched version running right now.

**Review by ChrisRx — APPROVED** [review]
I tested this as well, and everything worked for me, I'll go ahead and get this merged and then I can merge #21 to build the image.  Thanks for the PR, this is great!

**Comment by alexellis** [comment]
I couldn't get it to work through a Kubernetes ingress. It seemed to want to connect directly to the IP on port 443. Any ideas? It was sat trying to join a game.

**Comment by ChrisRx** [comment]
@alexellis The way quakejs works it always needs a port to be specified and previously when the port was only implied, it was presuming port 80.  This fix ends up addressing the other scenario where an implicit port is used with https (which will end up being 443).  With that said, I think your issue sounds like a different one from this, if you didn't mind would you open up a new issue with details and steps to reproduce?  That way either myself and/or someone else can try and figure out what might be going.

**Comment by sokoow** [comment]
@ChrisRx @alexellis you probably need another parameter in for this to work - because the IP address of kube node may be different then ingress node, it's safer to assume we need both hostname/dns that ingress sees, and 443 as a port - probably to be checked/swapped in js code for references back to detected machine IP

**Pull request merged**
