### PR TITLE
Add prometheus instrumentation, count active ws conns

### PR DESCRIPTION
**Pull request by ktravis**
I then experimented by adding a rule group to my prometheus configuration:
```yaml
- name: example
  rules:
   - alert: ChallengerApproaches
     expr: deriv(quake_active_connections[2m]) > .001 and ON() quake_active_connections == 1
     for: 30s
```

I haven't gotten the timing down yet, this alert took a while (~2m) to fire. This might be done better with a different metric type, or it just might need better PromQL to be written :smile:

### CODE REVIEW

**Comment by ChrisRx** [comment]
I love this!  I think it would be possible to use some of the telemetry over in #9 to define prometheus client metrics directly in the server.  I believe the connection-less OOB messages here can be queried quite frequently without affecting performance.  In particular, I think possibly `g_humanplayers` would be a good first metric, thoughts?

**Comment by ktravis** [comment]
Using the new `quakenet.GetStatus` I started adding a couple of other metrics, based on score and ping. There are certainly more that could be added (and probably additional metadata to include) but this seemed like a good building block.

I'm not sold on where I put the metrics-gathering loop or the metric definitions, I would definitely be open to moving them into a more suitable home. As mentioned in the `TODO`, there isn't currently a `context.Context` being passed in to the (client) `Server`, and the metrics interval is hard-coded to 5 seconds.

**Comment by ChrisRx** [comment]
What about moving the metrics [here](https://github.com/criticalstack/quake-kube/blob/546250c7a242a9cca04ee709733eb8e563d530f8/internal/quake/server/server.go#L15) (so they are colocated with what they represent) and moving the metrics producer to [here](https://github.com/criticalstack/quake-kube/blob/546250c7a242a9cca04ee709733eb8e563d530f8/internal/quake/server/server.go#L55)?  This ensures that it starts with the server, and the context from the server will ensure it gets cleaned up when the server is stopped.

**Comment by ktravis** [comment]
I wasn't sure how to get the server address from within that function - would I need to read `setup.cfg` in that case or pass it in another way?

**Pull request merged**
